import 'package:astro_prompt/config/api_endpoints.dart';
import 'package:flutter/foundation.dart';

/// Event Planner (Muhurtha) constants — mirrors web `muhurtha-screen.ts`.
class EventPlannerConfig {
  static const storagePrefix = 'teksage_event_planner_v3';
  static const ttlDays = 10;
  static const maxStartDaysAhead = 30;
  static const startDateOutOfRange =
      'Choose a date within the next 30 days.';
  static const publicSiteOrigin = 'https://my.teksage.app';
  /// Debug/local website origin (Next.js `npm run dev`). For a physical device,
  /// set this to your PC LAN IP, e.g. `http://192.168.1.10:3000`.
  static const localWebOrigin = 'http://127.0.0.1:3000';
  static const resultsPath = '/event-planner/results';
  static const shareCredit = 'Event Planner generated by Teksage Team';
  static const shareImageFileName = 'event_planner_result.png';

  /// Production builds → my.teksage.app. Debug → local web (or API host on :3000).
  static String get shareSiteOrigin {
    if (kReleaseMode) return publicSiteOrigin;
    return _debugWebOrigin();
  }

  static String _debugWebOrigin() {
    try {
      final api = Uri.parse(ApiEndpoint.mainUrl);
      final host = api.host;
      if (_isLocalHost(host)) {
        // Android emulator loopback to host machine.
        final webHost = host == '10.0.2.2' ? '10.0.2.2' : host;
        return 'http://$webHost:3000';
      }
    } catch (_) {}
    return localWebOrigin;
  }

  static bool _isLocalHost(String host) {
    return host == 'localhost' ||
        host == '127.0.0.1' ||
        host == '10.0.2.2' ||
        host.startsWith('192.168.') ||
        host.startsWith('10.');
  }

  static String buildResultsShareUrl({
    required String event,
    required String startDate,
    required String location,
  }) {
    final uri = Uri.parse('$shareSiteOrigin$resultsPath').replace(
      queryParameters: {
        'event': event,
        'start_date': startDate,
        'location': location,
      },
    );
    return uri.toString();
  }

  static String buildShareCaption(String pageUrl) =>
      '$shareCredit\n$pageUrl';

  static const eventTypes = [
    'Job Interview',
    'Financial Investment',
    'Learning New Skill',
    'Vehicle Purchase',
    'Travel',
    'Business Decisions',
  ];

  static const reasonCodes = [
    'nakshatra_not_suitable',
    'weekday_excluded',
    'thithi_excluded',
    'yoga_excluded',
    'thara_bala_excluded',
    'chandra_bala_excluded',
    'no_auspicious_window',
  ];
}
